[package]
name = "vodozemac-javascript"
version = "0.1.0"
edition = "2021"

[lib]
name = "vodozemac"
crate-type = ["cdylib"]

[dependencies.vodozemac]
git = "https://github.com/matrix-org/vodozemac"
rev = "ce947cc5759a1a647082d78213de9ee9cc080803"

[dependencies]
wasm-bindgen = "0.2.74"
js-sys = "0.3.51"
serde-wasm-bindgen = "0.3.0"
rand = { version = "0.7", features = ["wasm-bindgen"] }
