[package]
name = "vodozemac-javascript"
version = "0.1.0"
edition = "2021"

[lib]
name = "vodozemac"
crate-type = ["cdylib"]

[dependencies.vodozemac]
git = "https://github.com/matrix-org/vodozemac"
rev = "fa7e658147c4730dfe828f05e80520d2f3ebabdc"

[dependencies]
wasm-bindgen = "0.2.74"
js-sys = "0.3.51"
serde-wasm-bindgen = "0.3.0"
rand = { version = "0.7", features = ["wasm-bindgen"] }
