[package]
name = "vodozemac-javascript"
version = "0.1.0"
edition = "2021"

[lib]
name = "vodozemac"
crate-type = ["cdylib"]

[dependencies.vodozemac]
git = "https://github.com/matrix-org/vodozemac"
rev = "0df5cd161ee57f66d57e83f8b2b6f67704c3cabd"
features = ["js"]

[dependencies]
wasm-bindgen = "0.2.79"
js-sys = "0.3.56"
serde-wasm-bindgen = "0.4.2"
