[package]
name = "vodozemac-cpp"
version = "0.1.0"
edition = "2021"

[lib]
name = "vodozemac"
crate-type = ["staticlib"]

[dependencies.vodozemac]
git = "https://github.com/matrix-org/vodozemac"
rev = "ce947cc5759a1a647082d78213de9ee9cc080803"

[dependencies]
anyhow = "1.0.42"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
