[package]
name = "vodozemac-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "vodozemac"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "vodozemac"

[dependencies.vodozemac]
git = "https://github.com/matrix-org/vodozemac"
rev = "ce947cc5759a1a647082d78213de9ee9cc080803"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]
