[package]
name = "vodozemac-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "vodozemac"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "vodozemac"

[dependencies.vodozemac]
git = "https://github.com/matrix-org/vodozemac"
rev = "fa7e658147c4730dfe828f05e80520d2f3ebabdc"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]
