name: c++ tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install gtest
        uses: MarkusJx/googletest-installer@v1.1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Run the tests
        working-directory: ./cpp
        run: make test
